### ISSUE TITLE
Goals not being selected as expected.

### ISSUE THREAD

**Issue by SiliconOrchid** [GameDevEducation/Unity_AIBehavioursPackage#1]
Hi,  I think this is a bug - but exploring whether this just is intended behaviour that I don't currently understand?

In the demo, I'm not seeing the agent attempt to use lower priority goals, if a higher priority goal is present - but cannot be completed.

**To reproduce:**
* Fresh clone of Demo.
* Select the "SimStyleTestScene"
* Disable the entire "Interactables" gameobject in the hierarchy (i.e. the intent is to have zero smart objects in the world).
* Observe agent standing still and not engaging the "wander" goal.

Another way to demonstrate this, is to have just one or two smart objects present, and note that the agent only ever engages with those goals ... agent doesn't seem to switch to wandering.

_Loosely, I think this may be related to a type of "Goal.CanRun(...)" problem, but sorry - I can't be more constructively helpful until I get up to speed with this code! :-)_

**Comment by IainMcManus** [comment]
Cheers for reporting the issue. I had some bad logic in the GOAP Brain Wrapper where it wasn't checking it actually had valid interactables so always returned the default interaction desire letting the goal run. I've modified it to do a full check of there being currently usable ones present.
