### ISSUE TITLE
Question r.e. application of DontDestroyOnLoad within MonoBeheviourSingleton script

### ISSUE THREAD

**Issue by SiliconOrchid** [GameDevEducation/Unity_AIBehavioursPackage#2]
This query overlaps with the tutorial [Unity Design Patterns: Singleton Deep Dive](https://youtu.be/YzQ2Os-rLVA?feature=shared&t=1145)

I was experimenting with scene organisation.  I placed some of the demo's managers (e.g. `Blackboard Manager`) so they were  children of a new gameobject that I created(e.g.  `ScriptManagers`).   This meant that they are no longer root objects of the scene.

The impact is that, at runtime, they no longer appear as children of the 'DontDestroyOnLoad' object.  Additionally there is a console warning "DontDestroyOnLoad only works for root Gameobjects or components on root GameObjects...."

I haven't actually detected any impact to the correct operation of the singleton managers (everything _seems_ to be still working just fine) - but it's clearly no longer running as envisioned.

Within `MonoBeheviourSingleton` (around line 88),  might it be helpful to add something like a `transform.parent == null ` test, along with some sort of console warning to better flag up "hey, this should be a root object"?  

It would be in and around this code :

```
88      protected virtual void OnAwake()
89      {
90           DontDestroyOnLoad(gameObject);
91      }
``` 

Edit:  another idea is to just dynamically set the parent of these objects to be scene root at runtime startup.

**Comment by IainMcManus** [comment]
Ta for that. The deparenting them felt like the best option and it'll now flag an error when it does that but only when running in the editor.
