### ISSUE TITLE
Navigability/Range to SmartObject Interaction point

### ISSUE THREAD

**Issue by SiliconOrchid** [GameDevEducation/Unity_AIBehavioursPackage#3]
I've picked up on an edge case related to the distance between a `Smart Object`, it's corresponding `Interaction Marker` and the Navmesh.

Either: 

- the distance between the smartobject and the interaction can be set to be too large or, 
- the interaction point may not be navigable.

**To reproduce:**
- With a fresh clone of the demo.
- AI->Navigaton ;  Set the baking agent `Radius` to an unrealistically high value, such as "5" and re-bake the "Navmesh Surface".    The intent is to quickly create a scene with un-navigable objects by having an inappropriately small navmesh centred in the middle of the room.
- Note how the agent is stuck in the `SMState_UseInteractable`.      

The plan **is** being regenerated (you can see flickering in the game debugger), but it keeps instantly returning to the same goal in the same state.  The planning is working fine, the agent is just out of range to be able to complete the action.

I'm not sure what is a good way to address this;  adding a navigability test on each attempt by an agent to move towards something seems inappropriately expensive.  This strikes me as a design-time concern.     

Could this be the spark for a design-time "Wizard" tool (similar to the Unity-provided HDRP wizard) - a tool that we can run separately, that validates the design of a level in terms of distance-between-objects, etc?

_As a heads-up to a potential other issue, I noticed this issue whilst trying to reproduce a slightly different problem. In my own project, I have an agent stuck in `SMState_MoveTo` when supposedly arriving at InteractionMarker.   I'm still trying to decide if this is an implementation issue in my own project, or a bug in the goapsystem.  I haven't been able to reproduce this in the demo scene._

**Comment by SiliconOrchid** [comment]
Although this looks a bit weird, I actually think this is probably working as intended? 

**To reproduce:**
- With a fresh clone of the demo.  (i.e. default navmesh settings)
- Disable all smart objects, apart from "LargeObject_TV" and "LargeObject_BookShelfRight".   The intention is to keep the agent focussed on just two distinct things.
- Move the "InteractionMarker" of the TV, so it is behind the TV (between TV and wall).   The intention is to move the marker off the navmesh.
- Note how the agent appears to gets jammed in a goal refresh next to the bookshelf.  It's flip-flopping between going to the TV and Shelf, but gives the appearance of getting stuck at the bookshelf.

This seems to be showing that a navigability test to the InteractionMarker is in effect in this scenario.


Edit:    I guess further game-specific code, would have the agent switch to a different goal (e.g. a changing wander priority would kick in) which would mask this apparent loop?

**Comment by SiliconOrchid** [comment]
I have another scenario that I have in my own project, but I am unable to reproduce using your demo.     I have a suspicion that it all feeds into the same issue.

If I describe the behaviour, it might be possible to infer what's going on?

- I have 3 smart objects (light switches).   
    - These are essentially a cut+paste of your demo code for  `SmartObject_TV` - except with a different classname (`SmartObject_LightSwitch` & `LightSwitchInteraction_TogglePower`) 
    - An additional bit of code that actually changes the visibility of an associated Unity `Light` Component.
    - All three smart objects use the same code.
- Two of them work just fine (i.e. agents moves to them, changes their state on/off).   The visible light even toggles on/off nicely.  I believe the code is ok.
- The third object has a problem that I haven't been able to identify.   
    - The observed behaviour is that the agent approaches the `InteractionMarker` and the agent DOES appear to successfully arrive at that point.  
    - However, upon arrival the agent seems to get fully stuck in a `SMState_MoveTo` state.

Suspecting a navigability/placement issue, I have tried: 

- moving the problematic SmartObject (light switch) so that it is **placed fully within the baked navmesh area**.   
- I have also tried putting both the smartobject and its InteractionPoint close to the actual NavmeshSurface (exploring whether this might be a verticality issue).  That makes no difference.

Trying to provoke different behaviour, I have tried:

- Disable the two smartobjects that DO work.   
    - This causes the agent behaviour to completely change ... the agent instead ignores `GOAPGoal_UseInteractable` and just starts executing a `WanderGoal` plan.

This feel revealing.  **I think there is a miss-match between a goal being determined to be viable, and at least one corresponding action being able to complete the goal.**

**Comment by IainMcManus** [comment]
I'll take a look into it soon (likely next couple of weeks). From memory there is some logic that will attempt to search for a valid start location so it's possible at times it is finding something, getting through that stage, but can't get close enough. I think navmesh validation I can do efficiently for the interaction points by doing them in a batch on load and then afterwards only if the position etc changes.

**Comment by IainMcManus** [comment]
Notes from the fix:
- Navigability/Range to SmartObject Interaction point (reported by SiliconOrchid)
 - Added IsLocationReachable to INavigationInterface
 - Initial implementation just checks if the location is on the NavMesh. Will add further checks after interactable overhaul.
 - The validation is relatively cheap and will form a basis for larger changes to the interactable system.
