### ISSUE TITLE
Navigation Search Range meaning/function

### ISSUE THREAD

**Issue by SiliconOrchid** [GameDevEducation/Unity_AIBehavioursPackage#5]
Looking at `GOAPAction_UseInteractable` there is the exposed variable `NavigationSearchRange`.

I've found the naming/purpose of this to be a bit confusing:    

- I was expecting this to mean _"maximum distance from the agent, from which eligible targets can be selected "_   
    - i.e. a way to constrain the agent from selecting any interactables that are beyond a certain range.  
    - e.g. to prevent potential pinging backward and forward across a larger map.
- From tracing the code through, it seems that this feature actually means _"for a target that has already been selected, find the nearest navigable point to that target, constrained by NavigationSearchRange"_
    - i.e. having already selected a target, make sure that we can really get to it

code in question: 
- Variable defined and set:  `HybridGOAPExample.GOAPAction_UseInteractable.NavigationSearchRange` 
- passes through:  `StateMachine.SMState_CalculateMoveLocation`  ->  `OnEnterInternal(...)`  -> `MoveLocation = Navigation.FindNearestNavigableLocation(Self, MoveLocation, SearchRange);`
- argument ultimately ends up with:   `FrameworkEssentials.AI.Navigation_UnityNavMesh.FindNearestPoint(...)`

additional:

- https://youtu.be/JS3ney6Kqu0?feature=shared&t=866

issue actions:
- Could it be possible to review the current naming of `NavigationSearchRange` and/or include an inspector `Tooltip`?   
     - E.g. something along lines of `TargetNavigabilitySearchRange`.
- As a feature request, would it be useful to introduce a search-radius control, used to constrain target selection  (range from agents current position)?

**Comment by IainMcManus** [comment]
Notes from the fix:
- NavigationSearchRange has been renamed to ValidNavMeshSearchRange and given a tooltip
- Added support for setting an interactable search range. This is temporarily on the GOAPBrainWrapper pending an overhaul of the interaction system.
