### ISSUE TITLE
Navigation to Interaction-Marker problem.

### ISSUE THREAD

**Issue by SiliconOrchid** [GameDevEducation/Unity_AIBehavioursPackage#8]
This is quite the edge-case problem - but one that has been causing frustration for a few weeks, as the bizarre navigation behaviour has been difficult to identify and therefore replicate.   

I can now describe how to replicate, in the sample project, with a few simple additions.

_I think this may possibly be a problem with the Unity API `NavMesh.SamplePosition(...)` and not this project._

The issue occurs when there is a Navmesh that overlaps in a vertical plane.  

The issue relates to an interaction_marker not producing the expected navmesh result,  meaning an agent does not navigate to a spot nearby to an interaction_marker.

It seems to be that `NavMesh.SamplePosition(...)` will pick a spot on a Navmesh directly above,  rather than the Navmesh which is seemingly nearest.

**To reproduce:**

- Introduce a simple "mezzanine" along with a means to access it.    I've added this using 2 cubes (see image1).
- Rebake the navmesh to account for the new level.
- Using the TV smart object, place the interaction_point close to Navmesh edge.   This would be the point on the Navmesh that  we would expect the agent to use.   Don't actually put it over the Navmesh. (see image 2).
- To speed up debugging, remove other smart objects, leaving just a shelf and the TV.
- Run the game - observe how the agent navigates to a spot on the "mezzanine" - directly above the interaction_marker (see image 3).

**Expected behaviour:**

-  agent should navigate to a spot in front of TV (on lower level)

**Notes**

- If you put the navigation marker over the "expected navmesh" (e.g. in this example, a little further away from the TV, towards middle of room), it then behaves itself.    However, level design may not accommodate this ... and the point of using `NavMesh.SamplePosition(...)` is that it should select a point on the nearest navmesh.
- I've also added a "handrail cube" to stop the agent collider getting stuck at bottom of slope.
-  We might expect verticality to have reasonably become an issue, if the interaction_marker was placed in a higher position - e.g. being at the top of the TV screen could position it as being nearer to the navmesh above ... but in this example, I've gone out of my way to demonstrate the marker as being low-to-the-ground.

Image 1
![image](https://github.com/GameDevEducation/Unity_AIBehavioursPackage/assets/16468333/8400dfd3-6237-4e64-ab33-f2168d3d747d)

Image 2
![image](https://github.com/GameDevEducation/Unity_AIBehavioursPackage/assets/16468333/b91b1c18-1d9f-46c3-aa64-b11a9a71d29b)

Image 3
![image](https://github.com/GameDevEducation/Unity_AIBehavioursPackage/assets/16468333/06e704b7-fbaa-40e9-8875-1529dee56ae1)

**Comment by IainMcManus** [comment]
Sorry for the long delay on responding to this. I'll take a look into it. I'm not a fan of how SamplePosition works so I'll see if I can find an alternative. My preferred approach is a raycast down onto the navmesh and then a fallback search only if needed.

**Comment by IainMcManus** [comment]
It looks like unfortunately Unity doesn't expose a regular vertical raycast via the NavMesh (just the raycast parallel to it). I think (without replacing their navmesh system) the best I'll be able to do is have it do a regular physics raycast first then that'll at least allow SamplePositions with a shorter radius.

**Comment by IainMcManus** [comment]
Fixed as part of the 4.0.2 release. Adding the physics raycast to snap allows for the search ranges to be reduced enough to avoid the vertical overlap issues.
